### ISSUE TITLE
struct problem

### ISSUE THREAD

**Issue by wenmingMeng** [beacandler/R2CNN#1]
Thank your for sharing your code.I did not find the "logs" file in your project,but your "code structor" contains a "logs" file.Maybe i make something wrong? Looking forward to your reply.

**Comment by beacandler** [comment]
Thanks to your attention.
@wenmingMeng You can see 'logs folder' now, because I add it to .gitignore

**Comment by wenmingMeng** [comment]
Thank you very much!
