### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "roi_pooling_param"

### ISSUE THREAD

**Issue by gittigxuy** [beacandler/R2CNN#2]
make:进入目录'/home/xuy/code/R2CNN/src/lib/fastnms'
make: “adaptor.so”是最新的。
make:离开目录“/home/xuy/code/R2CNN/src/lib/fastnms”
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0407 13:56:59.493078 26902 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0407 13:56:59.493132 26902 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0407 13:56:59.493141 26902 _caffe.cpp:142] Net('/home/xuy/code/R2CNN/model/prototxt/test/TextBoxes-v3.prototxt', 1, weights='/home/xuy/code/R2CNN/model/caffemodel/TextBoxes-v2_iter_12w.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 483:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F0407 13:56:59.494863 26902 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/xuy/code/R2CNN/model/prototxt/test/TextBoxes-v3.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by gittigxuy** [comment]
我没有用docker进行编译，我参考了https://github.com/YuwenXiong/py-R-FCN，进行编译安装caffe

**Comment by beacandler** [comment]
@gittigxuy 可以的，代码是基于py-R-FCN的

**Comment by gittigxuy** [comment]
那为什么报错说找不到roi_pooling_param呢？原来的py-R-FCN里面是需要git microsoft的caffe,是不是caffe的版本问题呢？我应该怎么做呢？

**Comment by beacandler** [comment]
![image](https://user-images.githubusercontent.com/33446789/38475953-c5bc3446-3bdd-11e8-8cf7-b198a657de90.png)
可以看到docker安装的也是ms-caffe，编译成功后，应该不会出问题的。我建议下次把具体的错误信息贴出来，以便可以仔细排查。

**Comment by gittigxuy** [comment]
完整的报错信息已经贴到了1层，主要的问题是找不到roi pooling param

**Comment by beacandler** [comment]
![image](https://user-images.githubusercontent.com/33446789/38494596-18342864-3c29-11e8-9218-26bd4e950a5a.png)
@gittigxuy 
可以看到是在ROIPooling层出的错误，这说明不是笔者算法代码的错误，而是caffe编译的错误。我建议首先确保[R-FCN](https://github.com/YuwenXiong/py-R-FCN)的demo能够运行正确，然后再来运行RRCNN.

**Comment by gittigxuy** [comment]
R-FCN的demo已经成功运行，但是仍然报找不到roi_pooling
![default](https://user-images.githubusercontent.com/15090557/38607496-6169ecb6-3dab-11e8-8dfa-fbfcca8e9566.png)

我的操作步骤如下：
在r2cnn的根目录下
1）git clone https://github.com/Microsoft/caffe.git
2）可以成功编译Microsoft/caffe的make以及make pycaffe
3)改一下demo.py里面的模型路径

![default](https://user-images.githubusercontent.com/15090557/38608147-2a6284f6-3dad-11e8-9aaa-49f95d8e171e.png)


麻烦作者重新git一下你这个repo，看看在你的环境下是否会出现我的问题，谢谢了

**Comment by beacandler** [comment]
@gittigxuy 
你先确保下demo.sh调用的是ms-caffe？

**Comment by gittigxuy** [comment]
很对，系统默认调用了其他的caffe的python接口，将环境变量改一下就好了，谢谢了

**Comment by gittigxuy** [comment]
跑demo.py的时候遇到了out of memory的错误，显卡是980ti,应该能跑得动demo吧？想将batch_size改小一些，在哪个文件改呢？
