### ISSUE TITLE
执行test.sh，zip entry not valid:result

### ISSUE THREAD

**Issue by gittigxuy** [beacandler/R2CNN#3]
之前自己跑其他模型，获得一个icdar2015格式的结果，想要用eval_icdar15.py进行测试，但是报错了

![default](https://user-images.githubusercontent.com/15090557/38612626-e73804c8-3db9-11e8-9947-3aeb6c346258.png)

**Comment by beacandler** [comment]
@gittigxuy 
这个测试脚本是从[icdar2015](http://rrc.cvc.uab.es/?ch=4&com=mymethods&task=1)官网上下载的，把所有的*.txt直接压缩成submit.zip，然后进行测试（具体可以参照test.sh生成的submit.zip），具体可以参见代码。
